
namespace ProjectEulerProblems._1_20
{
    public class FibonacciNumber
    {
        /*
         Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        By starting with 1 and 2 , the first 10 terms will be: 
        1,2,3,5,8,13,21,34,55,89

        By considering the terms in the Fibonacci sequence whose values do not exceed four million,
        find the sum of the even-valued terms.

        */

        public static int PairNumbersSumInFibonacciSecuence()
        {
            int oldFibonacciNumber = 1;
            int flagNumber = 1;
            int lastFibonacciNumber = 1;

            int pairNumbersSum = 0;
            while(lastFibonacciNumber < 4000000)
            {
                //save old fibonacci number
                flagNumber = lastFibonacciNumber;
                //Generate new fibonacci number
                lastFibonacciNumber = oldFibonacciNumber + lastFibonacciNumber;
                //Update oldFibonacciNumber
                oldFibonacciNumber = flagNumber;
                //Compare if it's a pair number
                if (lastFibonacciNumber % 2 == 0)
                    pairNumbersSum += lastFibonacciNumber;
            }

            return pairNumbersSum;
        }
    }
}
